alter table public.calls
  add column if not exists interpretation_enabled boolean not null default true,
  add column if not exists caller_spoken_language text not null default 'English' check (char_length(caller_spoken_language) between 1 and 80),
  add column if not exists caller_heard_language text not null default 'English' check (char_length(caller_heard_language) between 1 and 80),
  add column if not exists callee_spoken_language text not null default 'Spanish' check (char_length(callee_spoken_language) between 1 and 80),
  add column if not exists callee_heard_language text not null default 'Spanish' check (char_length(callee_heard_language) between 1 and 80),
  add column if not exists interpretation_started_at timestamptz,
  add column if not exists interpretation_ended_at timestamptz,
  add column if not exists interpreted_seconds integer not null default 0 check (interpreted_seconds >= 0);

create table if not exists public.call_interpretation_metrics (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.calls(id) on delete cascade,
  source_user_id uuid not null references auth.users(id) on delete cascade,
  target_user_id uuid not null references auth.users(id) on delete cascade,
  utterance_id text not null,
  input_started_at timestamptz,
  transcription_completed_at timestamptz,
  first_audio_at timestamptz,
  output_completed_at timestamptz,
  first_audio_latency_ms integer check (first_audio_latency_ms >= 0),
  total_latency_ms integer check (total_latency_ms >= 0),
  interruption_count integer not null default 0 check (interruption_count >= 0),
  recovery_count integer not null default 0 check (recovery_count >= 0),
  error_count integer not null default 0 check (error_count >= 0),
  created_at timestamptz not null default now(),
  unique (call_id, source_user_id, utterance_id),
  check (source_user_id <> target_user_id)
);

create table if not exists public.call_usage_charges (
  call_id uuid not null references public.calls(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  seconds_charged integer not null default 0 check (seconds_charged >= 0),
  updated_at timestamptz not null default now(),
  primary key (call_id, user_id)
);

create index if not exists call_interpretation_metrics_call_idx on public.call_interpretation_metrics(call_id, created_at);
create index if not exists call_interpretation_metrics_latency_idx on public.call_interpretation_metrics(call_id, first_audio_latency_ms) where first_audio_latency_ms is not null;
create index if not exists call_usage_charges_user_idx on public.call_usage_charges(user_id, updated_at desc);

alter table public.call_interpretation_metrics enable row level security;
alter table public.call_usage_charges enable row level security;

drop policy if exists "Participants read call interpretation metrics" on public.call_interpretation_metrics;
create policy "Participants read call interpretation metrics" on public.call_interpretation_metrics for select
using (exists (
  select 1 from public.calls
  where calls.id = call_interpretation_metrics.call_id
    and (calls.caller_id = auth.uid() or calls.callee_id = auth.uid())
));

drop policy if exists "Users read own interpreted usage charges" on public.call_usage_charges;
create policy "Users read own interpreted usage charges" on public.call_usage_charges for select
using (auth.uid() = user_id);

create or replace function public.record_interpreted_usage(
  p_call_id uuid,
  p_user_id uuid,
  p_total_seconds integer
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  previous_seconds integer;
  delta_seconds integer;
  selected_plan text;
  selected_period_start date;
  selected_period_end date;
begin
  if p_total_seconds < 0 or not exists (
    select 1 from public.calls
    where id = p_call_id and p_user_id in (caller_id, callee_id)
  ) then
    raise exception using message = 'invalid_interpreted_usage', errcode = 'P0001';
  end if;

  insert into public.call_usage_charges (call_id, user_id, seconds_charged)
  values (p_call_id, p_user_id, 0)
  on conflict (call_id, user_id) do nothing;

  select seconds_charged into previous_seconds
  from public.call_usage_charges
  where call_id = p_call_id and user_id = p_user_id
  for update;

  delta_seconds := greatest(0, p_total_seconds - previous_seconds);
  if delta_seconds = 0 then return 0; end if;

  select coalesce((
    select plan_id from public.subscription_entitlements
    where user_id = p_user_id and status in ('active', 'trialing', 'grace_period')
      and (expires_at is null or expires_at > now())
  ), 'free') into selected_plan;

  if selected_plan = 'free' then
    selected_period_start := current_date;
    selected_period_end := current_date;
  else
    selected_period_start := date_trunc('month', current_date)::date;
    selected_period_end := (date_trunc('month', current_date) + interval '1 month - 1 day')::date;
  end if;

  insert into public.usage_periods (user_id, period_start, period_end, plan_id, seconds_used, updated_at)
  values (p_user_id, selected_period_start, selected_period_end, selected_plan, delta_seconds, now())
  on conflict (user_id, period_start) do update
  set seconds_used = usage_periods.seconds_used + excluded.seconds_used,
      plan_id = excluded.plan_id,
      period_end = excluded.period_end,
      updated_at = now();

  update public.call_usage_charges
  set seconds_charged = p_total_seconds, updated_at = now()
  where call_id = p_call_id and user_id = p_user_id;

  return delta_seconds;
end;
$$;

revoke all on table public.call_interpretation_metrics from anon, authenticated, service_role;
revoke all on table public.call_usage_charges from anon, authenticated, service_role;
revoke all on sequence public.call_interpretation_metrics_id_seq from anon, authenticated, service_role;
revoke all on function public.record_interpreted_usage(uuid, uuid, integer) from public;

grant select, insert, update on table public.call_interpretation_metrics to service_role;
grant select, insert, update on table public.call_usage_charges to service_role;
grant usage, select on sequence public.call_interpretation_metrics_id_seq to service_role;
grant execute on function public.record_interpreted_usage(uuid, uuid, integer) to service_role;
