create table if not exists public.calls (
  id uuid primary key default gen_random_uuid(),
  room_name text not null unique check (char_length(room_name) between 16 and 160),
  caller_id uuid not null references auth.users(id) on delete cascade,
  callee_id uuid not null references auth.users(id) on delete cascade,
  contact_id uuid references public.contacts(id) on delete set null,
  call_type text not null check (call_type in ('voice', 'video', 'business_video')),
  status text not null default 'ringing' check (status in ('ringing', 'accepted', 'active', 'declined', 'ended', 'missed', 'busy', 'failed', 'canceled')),
  ringing_at timestamptz not null default now(),
  answered_at timestamptz,
  ended_at timestamptz,
  ended_by uuid references auth.users(id) on delete set null,
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  decline_reason text check (char_length(decline_reason) <= 80),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (caller_id <> callee_id)
);

create table if not exists public.call_events (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.calls(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  event_type text not null check (event_type in ('created', 'ringing', 'accepted', 'active', 'declined', 'ended', 'missed', 'busy', 'failed', 'canceled', 'reconnecting', 'reconnected')),
  details jsonb not null default '{}'::jsonb check (jsonb_typeof(details) = 'object'),
  created_at timestamptz not null default now()
);

create table if not exists public.user_presence (
  user_id uuid primary key references auth.users(id) on delete cascade,
  status text not null default 'offline' check (status in ('online', 'offline', 'available', 'busy', 'ringing', 'in_call')),
  active_call_id uuid references public.calls(id) on delete set null,
  last_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists calls_caller_history_idx on public.calls(caller_id, created_at desc);
create index if not exists calls_callee_history_idx on public.calls(callee_id, created_at desc);
create index if not exists calls_incoming_idx on public.calls(callee_id, status, ringing_at desc);
create index if not exists calls_outgoing_idx on public.calls(caller_id, status, ringing_at desc);
create index if not exists calls_active_room_idx on public.calls(room_name) where status in ('accepted', 'active');
create index if not exists call_events_call_idx on public.call_events(call_id, created_at);
create index if not exists user_presence_status_idx on public.user_presence(status, last_seen_at desc);

alter table public.calls enable row level security;
alter table public.call_events enable row level security;
alter table public.user_presence enable row level security;

create policy "Participants read own calls" on public.calls for select
using (auth.uid() = caller_id or auth.uid() = callee_id);

create policy "Participants read own call events" on public.call_events for select
using (exists (
  select 1 from public.calls
  where calls.id = call_events.call_id
    and (calls.caller_id = auth.uid() or calls.callee_id = auth.uid())
));

create policy "Users read own presence" on public.user_presence for select using (auth.uid() = user_id);
create policy "Users update own presence" on public.user_presence for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.finalize_interpreter_call()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  if new.status in ('declined', 'ended', 'missed', 'busy', 'failed', 'canceled') then
    new.ended_at = coalesce(new.ended_at, now());
    if new.answered_at is not null then
      new.duration_seconds = greatest(0, floor(extract(epoch from (new.ended_at - new.answered_at)))::integer);
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists on_interpreter_call_updated on public.calls;
create trigger on_interpreter_call_updated before update on public.calls
for each row execute procedure public.finalize_interpreter_call();

create or replace function public.ensure_interpreter_presence()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.user_presence (user_id, status, last_seen_at)
  values (new.id, 'offline', now())
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_interpreter_presence_user_created on auth.users;
create trigger on_interpreter_presence_user_created after insert on auth.users
for each row execute procedure public.ensure_interpreter_presence();

insert into public.user_presence (user_id, status, last_seen_at)
select id, 'offline', now() from auth.users
on conflict (user_id) do nothing;

create or replace function public.reserve_interpreter_call(
  p_call_id uuid,
  p_room_name text,
  p_caller_id uuid,
  p_callee_id uuid,
  p_contact_id uuid,
  p_call_type text
)
returns public.calls
language plpgsql
security definer
set search_path = public
as $$
declare
  created_call public.calls;
begin
  perform pg_advisory_xact_lock(hashtextextended(least(p_caller_id::text, p_callee_id::text), 0));
  perform pg_advisory_xact_lock(hashtextextended(greatest(p_caller_id::text, p_callee_id::text), 0));

  if exists (
    select 1 from public.calls
    where status in ('ringing', 'accepted', 'active')
      and (caller_id in (p_caller_id, p_callee_id) or callee_id in (p_caller_id, p_callee_id))
  ) then
    raise exception using message = 'participant_busy', errcode = 'P0001';
  end if;

  insert into public.calls (id, room_name, caller_id, callee_id, contact_id, call_type)
  values (p_call_id, p_room_name, p_caller_id, p_callee_id, p_contact_id, p_call_type)
  returning * into created_call;

  insert into public.call_events (call_id, actor_id, event_type)
  values (p_call_id, p_caller_id, 'created'), (p_call_id, p_caller_id, 'ringing');

  insert into public.user_presence (user_id, status, active_call_id, last_seen_at, updated_at)
  values
    (p_caller_id, 'busy', p_call_id, now(), now()),
    (p_callee_id, 'ringing', p_call_id, now(), now())
  on conflict (user_id) do update
  set status = excluded.status, active_call_id = excluded.active_call_id, last_seen_at = now(), updated_at = now();

  return created_call;
end;
$$;

revoke all on table public.calls from anon, authenticated, service_role;
revoke all on table public.call_events from anon, authenticated, service_role;
revoke all on table public.user_presence from anon, authenticated, service_role;
revoke all on sequence public.call_events_id_seq from anon, authenticated, service_role;
revoke all on function public.reserve_interpreter_call(uuid, text, uuid, uuid, uuid, text) from public;

grant select, insert, update, delete on table public.calls to service_role;
grant select, insert on table public.call_events to service_role;
grant select, insert, update on table public.user_presence to service_role;
grant usage, select on sequence public.call_events_id_seq to service_role;
grant execute on function public.reserve_interpreter_call(uuid, text, uuid, uuid, uuid, text) to service_role;
